- name: install docker
  hosts: "*"
  tasks:
    - name: install docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        update_cache: yes
    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg
    - name: add docker repository
      apt_repository:
        filename: docker
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
        state: present
    - name: install docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          #- docker-scan-plugin
          - docker-compose-plugin
        update_cache: yes
    - name: add user to docker
      ansible.builtin.user:
        name: ajeya
        groups: docker
        state: present
        append: yes
