- name: upgrade linux
  hosts: "*"
  tasks:
    - name: Update & Upgrade
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
      register: apt_update_status

    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
