version: "3.7"

services:
  ansibleapp:
#    build:
#      context: .
    image: ansibleapp
    container_name: ansibleapp
    restart: unless-stopped
    volumes:
      - ./hosts:/etc/ansible/hosts
      - ./ansible.cfg:/etc/ansible/ansible.cfg
      - ./playbook:/playbook
    stdin_open: true
    tty: true